server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: "snap-campus"
#  web:
#    resources:
#      add-mappings: true
#  mvc:
#    throw-exception-if-no-handler-found: false
  datasource:
    url: url
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect #추가
        default_batch_fetch_size: 100
        show_sql: false
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  profiles:
#    include: secret
    active: prod
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
cloud:
  aws:
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: ap-northeast-2
    stack:
      auto: false
aws:
  s3:
    bucket: bucket
  ses:
    access_key: access_key
    secret_key: secret_key
